---
title: "DATA608 - Story 3"
author: "Glen Dale Davis"
date: "2023-09-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages:

```{r packages, warning=FALSE, message=FALSE}
library(geojsonio)
library(mapproj)
library(maptools)
library(RColorBrewer)
library(rgeos)
library(rgdal)
library(tidyverse)
library(cowplot)

```

## Firearm Mortality Data:

```{r data1}
#Geojson File Source: https://team.carto.com/u/andrew/tables/andrew.us_states_hexgrid/public/map
my_url <- "https://raw.githubusercontent.com/geedoubledee/Story3/main/us_states_hexgrid.geojson"
geo_df <- geojson_read(my_url, what = "sp")
geo_df@data <- geo_df@data |>
    mutate(google_name = gsub(" \\(United States\\)", "", google_name))

#Firearm mortality data
firearm_mortality <- read.csv("https://raw.githubusercontent.com/geedoubledee/Story3/main/cdc_nchs_firearm_mortality_by_state.csv")
firearm_mortality$STATE <- state.name[match(firearm_mortality$STATE,state.abb)]
firearm_mortality <- firearm_mortality |>
    filter(YEAR == 2021 | YEAR == 2005) |>
    arrange(STATE, YEAR) |>
    mutate(RATE_CHANGE_SINCE_2005 = RATE - lag(RATE)) |>
    filter(YEAR == 2021)

# Fortify
geo_fort <- fortify(geo_df, region="google_name")
geo_fort <- geo_fort |>
    filter(id != "District of Columbia") |>
    left_join(firearm_mortality, by = c("id" = "STATE")) |>
    mutate(bin = as.factor(case_when(RATE < 5 ~ 5,
                                     RATE < 10 ~ 10,
                                     RATE < 15 ~ 15,
                                     RATE < 20 ~ 20,
                                     RATE < 25 ~ 25,
                                     RATE < 30 ~ 30,
                                     RATE >= 30 ~ 35)))

# Calculate hexagon centers for labeling purposes:
centers <- cbind.data.frame(data.frame(gCentroid(geo_df, byid = TRUE),
                                       id = geo_df@data$iso3166_2))
centers <- centers |>
    filter(id != "DC")

```

## Firearm Mortality Plot:

```{r plot1}

#Prepare pallet
my_palette <- brewer.pal(n = 7, name = "OrRd")

# Plot the shape
p1 <- ggplot() +
    geom_polygon(data = geo_fort, aes(fill = bin, x = long, y = lat,
                                      group = group),
                 linewidth = 0, alpha = 0.9) +
    geom_text(data = centers, aes(x = x, y = y, label = id), color="black",
              size = 3, alpha = 0.6) +
    scale_fill_manual(values = my_palette,
                      name = "Death Rate Per 100,000 People",
                      guide = guide_legend(keyheight = unit(3, units = "mm"),
                                           keywidth = unit(12, units = "mm"),
                                           label.position = "bottom",
                                           title.position = 'top', nrow=1)) +
    theme_void() +
    theme(plot.title = element_text(hjust = 0.5), legend.position = "bottom") +
    coord_map()

```

## Gun Law Strictness Data:

```{r data2}
my_url <- "https://raw.githubusercontent.com/geedoubledee/Story3/main/strictest-gun-laws-by-state.csv"
gun_law_strictness <- read.csv(my_url)
keep <- c("state", "gunLawsGiffordGrade")
cols <- c("STATE", "Gifford")
gun_law_strictness <- gun_law_strictness |>
    select(all_of(keep))
colnames(gun_law_strictness) <- cols
gun_law_strictness$Gifford <- gsub("[^[:alnum:]]", "",
                                   gun_law_strictness$Gifford)
levels <- c("Most Lax", "More Lax", "Lax", "Strict", "Strictest")
gun_law_strictness <- gun_law_strictness |>
    mutate(
        Strictness = as.factor(case_when(
            Gifford < "B" ~ "Strictest",
            Gifford < "C" ~ "Strict",
            Gifford < "D" ~ "Lax",
            Gifford < "F" ~ "More Lax",
            Gifford >= "F" ~ "Most Lax"))
        )

gun_law_strictness$Strictness <- factor(gun_law_strictness$Strictness,
                                        levels = levels)
combined <- firearm_mortality |>
    left_join(gun_law_strictness, by = "STATE") |>
    mutate(RANK = row_number(desc(RATE)),
           ABBREV = state.abb[match(STATE,state.name)])

```

## Gun Law Strictness Plot:

```{r plot2}
p2 <- combined |>
    ggplot(aes(x = RANK, y = RATE_CHANGE_SINCE_2005, fill = Strictness)) +
    geom_point(shape = 21, size = 2, color = "#3F007D", alpha = 0.6) +
    scale_color_brewer(palette = "Purples", aesthetics = "fill",
                       direction = -1) +
    labs(x = "State's Current Ranking (1 Being Worst)",
         y = "Death Rate Increase Since 2005",
         fill = "Gun Law Strictness") +
    theme_classic() +
    theme(legend.position = "right") +
    coord_flip()

```

```{r plots_paired}
p <- plot_grid(p1, p2, nrow = 1, rel_widths = c(1.15, 1), rel_heights = c(1, 1))
title <- ggdraw() +
    draw_label("Firearm Death Rates Up in States with Most Lax Gun Laws",
               fontface='bold')
plot_grid(title, p, ncol = 1, rel_heights=c(0.1, 2))

```